# -*- coding: utf-8 -*-
"""day5_project_[Anila].py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/121RDWAM9jF0k8Qazp3F31ctkwad7hMdK
"""

#day 5_4: Filter temperature outliers (> 30°C), save to CSV.
from google.colab import files
uploaded = files.upload()

import pandas as pd
df=pd.read_csv('strawberryplantdata_new.csv')
filtered_df=df[df['temperature']>30]
filtered_df.to_csv('filtered_plant_data.csv',index=False)
print("Filtered data saved to 'filtered_plant_data.csv")